# Generated by Django 4.1.5 on 2023-01-13 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('cartnum', models.CharField(db_column='CARTNUM', max_length=20, primary_key=True, serialize=False)),
                ('cartcount', models.IntegerField(db_column='CARTCOUNT')),
            ],
            options={
                'db_table': 'CART',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Category1',
            fields=[
                ('category1', models.CharField(db_column='CATEGORY1', max_length=20, primary_key=True, serialize=False)),
                ('category1name', models.CharField(db_column='CATEGORY1NAME', max_length=20)),
            ],
            options={
                'db_table': 'CATEGORY1',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Category2',
            fields=[
                ('category2', models.CharField(db_column='CATEGORY2', max_length=20, primary_key=True, serialize=False)),
                ('category2name', models.CharField(db_column='CATEGORY2NAME', max_length=20)),
            ],
            options={
                'db_table': 'CATEGORY2',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Doc',
            fields=[
                ('docnum', models.CharField(db_column='DOCNUM', max_length=20, primary_key=True, serialize=False)),
                ('docwdate', models.DateField(db_column='DOCWDATE')),
                ('docrdate', models.DateField(blank=True, db_column='DOCRDATE', null=True)),
                ('docstate', models.CharField(db_column='DOCSTATE', max_length=20)),
                ('docrejectreason', models.CharField(blank=True, db_column='DOCREJECTREASON', max_length=20, null=True)),
                ('doccancled', models.IntegerField(blank=True, db_column='DOCCANCLED', null=True)),
            ],
            options={
                'db_table': 'DOC',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('ordernum', models.CharField(db_column='ORDERNUM', max_length=20, primary_key=True, serialize=False)),
                ('orderdate', models.DateField(blank=True, db_column='ORDERDATE', null=True)),
                ('orderstate', models.CharField(db_column='ORDERSTATE', max_length=20)),
                ('orderaddr', models.CharField(blank=True, db_column='ORDERADDR', max_length=20, null=True)),
            ],
            options={
                'db_table': 'ORDER',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('prodnum', models.CharField(db_column='PRODNUM', max_length=20, primary_key=True, serialize=False)),
                ('prodname', models.CharField(db_column='PRODNAME', max_length=20)),
                ('prodprice', models.IntegerField(db_column='PRODPRICE')),
                ('prodimg', models.CharField(db_column='PRODIMG', max_length=20)),
            ],
            options={
                'db_table': 'PRODUCT',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reqterm',
            fields=[
                ('termyearmonth', models.CharField(db_column='TERMYEARMONTH', max_length=20, primary_key=True, serialize=False)),
                ('termstartdate', models.DateField(db_column='TERMSTARTDATE')),
                ('termenddate', models.DateField(db_column='TERMENDDATE')),
                ('termavailable', models.IntegerField(db_column='TERMAVAILABLE')),
            ],
            options={
                'db_table': 'REQTERM',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('reqnum', models.CharField(db_column='REQNUM', max_length=20, primary_key=True, serialize=False)),
                ('reqcount', models.IntegerField(db_column='REQCOUNT')),
                ('reqprice', models.IntegerField(db_column='REQPRICE')),
                ('reqdate', models.DateField(db_column='REQDATE')),
                ('reqapvdate', models.DateField(blank=True, db_column='REQAPVDATE', null=True)),
                ('reqstate', models.CharField(db_column='REQSTATE', max_length=20)),
                ('reqstaging', models.CharField(blank=True, db_column='REQSTAGING', max_length=20, null=True)),
                ('reqrejectreason', models.CharField(blank=True, db_column='REQREJECTREASON', max_length=20, null=True)),
                ('reqcancled', models.IntegerField(db_column='REQCANCLED')),
            ],
            options={
                'db_table': 'REQUEST',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('usernum', models.CharField(db_column='USERNUM', max_length=20, primary_key=True, serialize=False)),
                ('userid', models.CharField(db_column='USERID', max_length=20)),
                ('userpwd', models.CharField(db_column='USERPWD', max_length=20)),
                ('username', models.CharField(db_column='USERNAME', max_length=20)),
                ('userathority', models.IntegerField(db_column='USERATHORITY')),
                ('userposition', models.CharField(blank=True, db_column='USERPOSITION', max_length=20, null=True)),
                ('userdept', models.CharField(blank=True, db_column='USERDEPT', max_length=20, null=True)),
            ],
            options={
                'db_table': 'USER',
                'managed': False,
            },
        ),
    ]
